<?php
/**
 * The default invoices loop for the
 * content-invoices.php template part.
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-invoices/loops/ directory
 * located in your theme.
*/
?>
<?php do_action( 'it_exchange_content_invoices_before_unpaid_invoices_loop' ); ?>
<h3 class="customer-invoices-subheading"><?php _e( 'Unpaid Invoices', 'LION' ); ?></h3>
<?php while ( it_exchange( 'invoices', 'exist', array( 'invoice_status' => array( 'unpaid', 'due-now', 'late', 'pending' ) ) ) ) : ?>
	<?php do_action( 'it_exchange_content_invoices_begin_unpaid_invoices_loop' ); ?>
	<div class="it-exchange-invoice it-exchang-invoice-unpaid">
			<?php it_exchange_get_template_part( 'content', 'invoices/loops/invoice-info' ); ?>
	</div>
	<?php do_action( 'it_exchange_content_invoices_end_unpaid_invoices_loop' ); ?>
<?php endwhile; ?>
<?php it_exchange( 'invoices', 'reset' ); ?>
<?php do_action( 'it_exchange_content_invoices_after_unpaid_invoices_loop' ); ?>
