<?php
/**
 * Default template for displaying the a single
 * invoice product invalid-link template part.
 *
 * @since 1.0.8
 * @version 1.0.8
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>
<?php do_action( 'it_exchange_content_invoice_product_before_invalid_wrap' ); ?>
<div class="it-exchange-invoice-section it-exchange-invoice-invalid it-exchange-clearfix">
	<?php do_action( 'it_exchange_content_invoice_product_begin_invalid_wrap' ); ?>
	<h3><?php _e( 'Protected', 'LION' ); ?></h3>
	<p>
		<?php _e( 'This invoice may only be accessed using the link in your email.' ); ?>
	</p>
	<?php do_action( 'it_exchange_content_invoice_product_end_invalid_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_invoice_product_after_invalid_wrap' ); ?>
