<?php
/**
 * Default template for displaying the a single
 * invoice product notes template part.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>
<?php do_action( 'it_exchange_content_invoice_product_before_notes_wrap' ); ?>
<div class="it-exchange-invoice-section it-exchange-invoice-notes">
	<?php do_action( 'it_exchange_content_invoice_product_begin_notes_wrap' ); ?>
		<div class="it-exchange-invoice-note">
			[notes theme api call]
		</div>
	<?php do_action( 'it_exchange_content_invoice_product_end_notes_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_invoice_product_after_notes_wrap' ); ?>
