<?php
/**
 * Default template for displaying the a single
 * invoice product print template part.
 *
 * @since CHANGEME
 * @version CHANGEME
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>
<?php do_action( 'it_exchange_content_invoice_product_before_print_wrap' ); ?>
<div class="it-exchange-invoice-print it-exchange-clearfix">
	<?php do_action( 'it_exchange_content_invoice_product_begin_print_wrap' ); ?>
	<div class="it-exchange-right">
		<?php it_exchange( 'invoice', 'print' ); ?>
	</div>
	<?php do_action( 'it_exchange_content_invoice_product_end_print_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_invoice_product_after_print_wrap' ); ?>
