<?php
/**
 * Default template for displaying the a single
 * invoice product images template part.
 *
 * @since CHANGEME
 * @version CHANGEME
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>

<?php if ( it_exchange( 'product', 'has-images' ) ) : ?>
	<?php do_action( 'it_exchange_invoices_addon_content_product_before_product_images_element' ); ?>
	<div class="it-exchange-invoice-section <?php echo ( ! it_exchange( 'product', 'has-images' ) ) ? ' it-exchange-product-no-images' : 'it-exchange-product-has-images'; ?> it-exchange-clearfix">
		<div class="it-exchange-product-images">
			<div class="it-exchange-column-inner">
				<?php it_exchange( 'product', 'gallery' ); ?>
			</div>
		</div>
	</div>
	<?php do_action( 'it_exchange_invoices_addon_content_product_after_product_images_element' ); ?>
<?php endif; ?>