<?php
/**
 * Default template for displaying the a single
 * invoice product resend-email template part.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>
<?php do_action( 'it_exchange_content_invoice_product_before_resend_wrap' ); ?>
<div class="it-exchange-invoice-section it-exchange-invoice-resend it-exchange-clearfix">
	<?php do_action( 'it_exchange_content_invoice_product_begin_resend_wrap' ); ?>
	<h3><?php _e( 'Protected', 'LION' ); ?></h3>
	<p>
		<?php printf( __( 'This invoice may only be accessed using the link in your email. %sResend email%s', 'LION' ), '<a rel="nofolow" href="' . add_query_arg( 'it-exchange-invoice-resend', '1' ) . '">', '</a>' ); ?>
	</p>
	<?php do_action( 'it_exchange_content_invoice_product_end_resend_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_invoice_product_after_resend_wrap' ); ?>
