<?php
/**
 * This file contains the markup for the email invoice details.
 *
 * @since   2.0.0
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/email/invoice/details.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; background: <?php it_exchange( 'email', 'body-background-color' ); ?>; padding-bottom: 20px; margin: 0 auto;" class="wrapper body-bkg-color">
			<tr>
				<td valign="top" style="padding: 0 25px; ">
					<table width="100%">
						<tr>
							<td style="padding-bottom: 20px; border-bottom: 1px solid <?php it_exchange( 'email', 'body-highlight-color' ); ?>">

								<?php if ( it_exchange( 'invoice', 'has-description' ) ): ?>
									<h4><?php _e( 'Description', 'LION' ); ?></h4>
									<p><?php it_exchange( 'invoice', 'description', 'format=value' ); ?></p>
								<?php endif; ?>

								<?php if ( it_exchange( 'invoice', 'has-terms' ) ): ?>
									<h4><?php _e( 'Terms', 'LION' ); ?></h4>
									<p><?php it_exchange( 'invoice', 'terms', 'format=value' ); ?></p>
								<?php endif; ?>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>
