<?php
/**
 * This file contains the markup for the email invoice totals.
 *
 * @since   1.10
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/email/invoice/totals.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; font-size: 1.2em; background: <?php it_exchange( 'email', 'body-background-color' ); ?>; padding-bottom: 20px; margin: 0 auto;" class="wrapper body-bkg-color">
			<tr>
				<td valign="top" style="padding: 0 25px;">
					<table width="100%" style="line-height: 1.2;">
						<tr>
							<td></td>
							<td style="padding: 10px 0;"><strong><?php _e( 'Payment', 'LION' ) ?></strong></td>
							<td align="right" style="padding: 10px 0;"><?php it_exchange( 'invoice', 'total-due', 'format=value' ); ?></td>
						</tr>

						<tr>
							<td></td>
							<td style="padding: 10px 0;"><strong><?php _e( 'Status', 'LION' ); ?></strong></td>
							<td align="right" style="padding: 10px 0;"><?php it_exchange( 'invoice', 'payment-status', 'format=label' ); ?></td>
						</tr>
					</table>
					<table width="100%" style="line-height: 1.2;">
						<tr align="center">
							<td></td>
							<td style="padding: 20px 0 30px 0;">
								<strong>
									<a style="display:block; background: <?php it_exchange( 'email', 'body-highlight-color' ); ?>; color: <?php it_exchange( 'email', 'body-button-color' ); ?>; text-decoration: none; padding: 10px 0; border-radius: 3px;" href="<?php it_exchange( 'invoice', 'permalink', 'format=value' ); ?>">
										<?php _e( 'View Invoice', 'LION' ); ?>
									</a>
								</strong>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>
