<?php
/**
 * Default template for displaying the a single
 * invoice product payment template part.
 *
 * @since 1.0.0
 * @version 1.0.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>
<?php do_action( 'it_exchange_content_invoice_product_before_payment_wrap' ); ?>
<div class="it-exchange-invoice-section it-exchange-invoice-payment it-exchange-clearfix">
	<?php do_action( 'it_exchange_content_invoice_product_begin_payment_wrap' ); ?>
		<div class="it-exchange-invoice-payment-amount">
			<?php it_exchange( 'invoice', 'payment-amount' ); ?>
		</div>
	<?php do_action( 'it_exchange_content_invoice_product_after_payment_amount' ); ?>

	<?php do_action( 'it_exchange_content_invoice_product_before_payment_status' ); ?>
		<div class="it-exchange-invoice-payment-status">
			<?php it_exchange( 'invoice', 'payment-status' ); ?>
		</div>
	<?php do_action( 'it_exchange_content_invoice_product_end_payment_wrap' ); ?>
</div>
<?php
// Only show payment options if invoice is paid or hash is correct
if ( it_exchange_invoice_addon_is_hash_valid_for_invoice() && ! in_array( it_exchange( 'invoice', 'get-payment-status', array( 'format' => 'value' ) ), array( 'pending', 'paid' ) ) ) :
	?><div class="it-exchange-invoice-sw"><?php
	it_exchange( 'product', 'superwidget' );
	?></div><?php
endif;
?>
<?php do_action( 'it_exchange_content_invoice_product_after_payment_wrap' ); ?>
