<?php
/**
 * The default template part for the no purchases found
 * in the content-invoices.php template part.
 *
 * @since 1.2.0
 * @version 1.2.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-invoices/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_invoices_before_no_invoices_found_element' ); ?>
<p class="it-exchange-no-invoices-found it-exchange-notice"><?php _e( 'No invoices found.', 'LION' ); ?></p>
<?php do_action( 'it_exchange_content_invoices_after_no_invoices_found_element' ); ?>
