<?php
/**
 * The default invoice-info loop for the content-purchases.php template part
 *
 * @since 1.1.0
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-purchases/loops/ directory
 * located in your theme.
*/
?>

<?php do_action( 'it_exchange_content_invoices_before_invoice_info_loop' ); ?>
<?php do_action( 'it_exchange_content_invoices_begin_invoice_info_loop' ); ?>
<?php
/**
 * Invoice attributes to include
 * Available elements:
 * date-issued, invoice-number, to, from
 * payment-amount, payment-status, view-more
 * terms, po-number, total-due, date-due
*/
$it_exchange_invoice_elements = array(
	'title',
	'summary',
);
?>
<?php foreach ( it_exchange_get_template_part_elements( 'content_purchases', 'invoice_fields', $it_exchange_invoice_elements ) as $detail ) : ?>
	<?php it_exchange_get_template_part( 'content-invoices/elements/' . $detail ); ?>
<?php endforeach; ?>
<?php do_action( 'it_exchange_content_invoices_end_invoice_info_loop' ); ?>
<?php do_action( 'it_exchange_content_invoices_after_invoice_info_loop' ); ?>
