<?php
/**
 * Default template for displaying the an exchange
 * customer's invoice(s).
 *
 * @since 1.2.0
 * @version 1.2.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
*/
?>

<?php do_action( 'it_exchange_content_invoices_before_wrap' ); ?>
<div id="it-exchange-invoices" class="it-exchange-wrap it-exchange-account">
<?php do_action( 'it_exchange_content_invoices_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<?php it_exchange( 'customer', 'menu' ); ?>

	<?php if ( it_exchange_invoices_addon_get_invoices_for_customer() ) : ?>
		<?php if ( it_exchange_invoices_addon_get_invoices_for_customer( false, array( 'invoice_status' => array( 'pending', 'late', 'unpaid', 'due-now' ) ) ) ) : ?>
			<?php it_exchange_get_template_part( 'content', 'invoices/loops/unpaid-invoices' ); ?>
		<?php endif; ?>
		<?php if ( it_exchange_invoices_addon_get_invoices_for_customer( false, array( 'invoice_status' => 'paid' ) ) ) : ?>
			<?php it_exchange_get_template_part( 'content', 'invoices/loops/paid-invoices' ); ?>
		<?php endif; ?>
	<?php else : ?>
		<?php it_exchange_get_template_part( 'content', 'invoices/elements/no-invoices-found' ); ?>
	<?php endif; ?>
<?php do_action( 'it_exchange_content_invoices_end_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_content_invoices_after_wrap' ); ?>
